---
- project:
    check:
      jobs:
        - ansible-tox-linters
        # - ansible-tox-molecule:
        #     required-projects:
        #       - github.com/ansible-security/ids_config
    gate:
      jobs:
        - ansible-tox-linters
        # - ansible-tox-molecule:
        #     required-projects:
        #       - github.com/ansible-security/ids_config
